# Generated by Django 3.1.1 on 2020-10-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20201020_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='trips', to='exam_app.User'),
        ),
    ]
