# Generated by Django 3.1.1 on 2020-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20201020_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
